---
-
  hosts: all
  gather_facts: true # this will make not to gather facts before running tasks
  
  vars_files:
   - servicesvar.yml

  tasks: 
    - name: Stop the services
      win_service:
        name: " {{ Service }} "
        state: stopped
...      

    


# you can also use
# loop:
#    - {name: 'Dinesh' , company: 'Generalmills'} You can call this by item.name and item.company 

...


# use same looping to stop the BITS and dhcp service




